### ISSUE TITLE
Sdk not connecting

### ISSUE THREAD

**Issue by 0xfave** [pontem-network/liquidswap-sdk#54]
## Expected Behavior
Make a swap
## Code
![Screenshot from 2024-10-16 12-05-07](https://github.com/user-attachments/assets/49596470-3319-49f1-8123-7b7841412e6e)
![Screenshot from 2024-10-16 12-06-09](https://github.com/user-attachments/assets/948070a8-8d22-4cf7-8e1e-b1b8a573ff4e)

## Actual Behavior
```shell
346 |                                           ...options
347 |                                   });
348 |                                   session[kCurrentStreamsCount] = 0;
349 |                                   session[kGracefullyClosing] = false;
350 | 
351 |                                   const isFree = () => session[kCurrentStreamsCount] < session.remoteSettings.maxConcurrentStreams;
                                                                        ^
TypeError: null is not an object (evaluating 'session.remoteSettings.maxConcurrentStreams')
      at isFree (/home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/node_modules/http2-wrapper/source/agent.js:351:67)
      at /home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/node_modules/http2-wrapper/source/agent.js:449:12
      at emit (node:events:180:48)
      at #onConnect (node:http2:718:13)
      at onConnect (node:http2:855:23)
      at emit (node:events:180:48)
      at handshake (node:net:115:14)
965 |             var _a;
966 |             // Force clean-up, because some packages (e.g. nock) don't do this.
967 |             request.destroy();
968 |             // Node.js <= 12.18.2 mistakenly emits the response `end` first.
969 |             (_a = request.res) === null || _a === void 0 ? void 0 : _a.removeAllListeners('end');
970 |             error = error instanceof timed_out_1.TimeoutError ? new TimeoutError(error, this.timings, this) : new RequestError(error.message, error, this);
                                                                                                                    ^
RequestError: ERR_HTTP2_ERROR: h2 is not supported
 code: "ERR_HTTP2_ERROR"

      at /home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/dist/source/core/index.js:970:111
      at native:1:1
      at native:1:1
      at /home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/node_modules/@szmarczak/http-timer/dist/source/index.js:46:17
      at /home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/node_modules/http2-wrapper/source/client-request.js:363:10
      at processTicksAndRejections (native:1:1)
      at #onConnect (node:http2:718:13)
      at onConnect (node:http2:855:23)
      at emit (node:events:180:48)
      at handshake (node:net:115:14)


Bun v1.1.24 (Linux x64)
```

## Steps to Reproduce the Problem

1. connect to sdk
2. try calculating rates

## Specifications

- Version: "@pontem/liquidswap-sdk": "^0.7.3",
- Platform: ubuntu

**Comment by 0xfave** [comment]
issue is from bun
use other package manager that supports http2
